version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      # アクセスログ・エラーログを外部に保存する
      - ./logs/nginx:/var/log/nginx
      # 設定ファイルを外部に保存する
      - ./nginx/conf.d:/etc/nginx/conf.d
      # Laravelプロジェクトと繋ぐ
      - ./laravel_app:/var/www/laravel_app
    ports:
      - 80:80
    networks:
      - akipon_app_network
    depends_on:
      # PHPの後に処理を実行しはじめる
      - phpfpm
    tty: true

  phpfpm:
    build:
      context: .
      dockerfile: ./phpfpm/Dockerfile
    volumes:
      - ./laravel_app:/var/www/laravel_app
    networks:
      - akipon_app_network
    depends_on:
      - mysql
    tty: true

  mysql:
    image: mysql@sha256:574b626bb89112cc406c23471ab968de7be5e598eecb5ecc3eecaaf0610d8050
    container_name: mysql
    ports:
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: root
    volumes:
      - ./mysql/init/:/docker-entrypoint-initdb.d
    networks:
      - akipon_app_network
    tty: true

networks:
  akipon_app_network:
