version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      # アクセスログ・エラーログを外部に保存する
      - ./logs/nginx:/var/log/nginx
      # 設定ファイルを外部に保存する
      - ./nginx/conf.d:/etc/nginx/conf.d
      # Laravelプロジェクトと繋ぐ
      - ./laravel_portfolio:/var/www/laravel_portfolio
    ports:
      - 58710:80
    networks:
      - akipon_app_network
    depends_on:
      # PHPの後に処理を実行しはじめる
      - phpfpm
    tty: true

  phpfpm:
    build:
      context: .
      dockerfile: ./phpfpm/Dockerfile
    volumes:
      - ./laravel_portfolio:/var/www/laravel_portfolio
    networks:
      - akipon_app_network
    depends_on:
      - mysql
    env_file:
      ./phpfpm/env/setting.env
    tty: true

  mysql:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    volumes: 
      - ./mysql/data:/var/lib/mysql
      - ./mysql/mysql_conf:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    env_file:
      ./mysql/env/setting.env
    networks:
      - akipon_app_network
    tty: true

networks:
  akipon_app_network:
